version: '3.8'

services:
  springboot-app:
    image: trainingimage
    ports:
      - 8000:8080
    depends_on:
      - mysqldb
    
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trainingdb